[phases.setup]
nixPkgs = ['nodejs_18', 'python39']

[phases.install]
cmds = [
    'npm install',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'